### ISSUE TITLE
Love it

### ISSUE THREAD

**Issue by hydezeke** [mondersky/tabscolor-vscode#13]
I often have files with the same name open (multiple remote servers) and needed a way to mark one as "do not work on this one" and this plugin has helped a great deal. Thanks!

![image](https://user-images.githubusercontent.com/8236489/188165788-27799754-6837-4abf-8c72-f931aab3aa5d.png)

No problems, just thanks :)

**Comment by mondersky** [comment]
You're welcome, I am happy to see that the extension has been helpful to you :) 
If you have some time please leave a feedback on the vs code page, that would help the extension reach more people !
