### ISSUE TITLE
Idea: add colors to files in the sidebar

### ISSUE THREAD

**Issue by sqmasep** [mondersky/tabscolor-vscode#14]
I imagine that with a true/false option

for example, instead of having this kind of files (see image), you would have each file with the color you've defined in settings.json
![image](https://user-images.githubusercontent.com/78935965/190860544-06813678-af96-464e-97f9-bc801a3b591b.png)

**Comment by mondersky** [comment]
Thanks for the suggestion, few other people have asked for this feature too, I'll definitely put it on the todo list
