### ISSUE TITLE
Is broken (don't work anymore) with last 1.72.0

### ISSUE THREAD

**Issue by nicolasmol** [mondersky/tabscolor-vscode#17]
Even after doing "repatch"
![Peek 07-10-2022 12-02](https://user-images.githubusercontent.com/61077647/194549342-7559e54a-d325-48e2-a7a5-4b307b26e748.gif)
`workbench.desktop.nls.js `(nls: "natural language search") is not always called and surely not the right place to apply the patch. 
In my case, it is not. 
Maybe because my IDE is French.
In example of https://github.com/be5invis/vscode-custom-css, I suggest you to patch 
`.../code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html`

**Comment by nicolasmol** [comment]
[EDIT]

**Comment by mondersky** [comment]
Hello, thanks for letting me now, unfortunately following the new release of vs code I am no more able to patch vs code without having the popup "your installation is corrupt..." appear. Sure there's another way to get this done but I must investigate further therefore I am pausing the development of this extension until I find the time to patch vs code in a much cleaner way. Thank you for all your efforts

**Comment by nicolasmol** [comment]
The warning message is not a big deal, as it is explained by https://github.com/be5invis/vscode-custom-css

**Comment by mondersky** [comment]
ok sounds good to me then. I'll update the extension soon with a friendly way of alerting people about the "corrupt" notification message

**Comment by mondersky** [comment]
the extension was updated to work with the last version, don't hesitate to let me know if you face any other issue.
