### ISSUE TITLE
Custom colors don't work with automatic colors based on file type

### ISSUE THREAD

**Issue by Zwornik** [mondersky/tabscolor-vscode#21]
Actually, custom colors can only be assigned to individual files, not file types, from right-click menu. 
Where can I change the default colours so I can automatically assign them according to file type?

**Comment by mondersky** [comment]
color by file type isn't accessible by right click, in order to assign a color to a specific file type, go to the extension's page and click on the settings gear > extension settings > By file Type

**Comment by Zwornik** [comment]
Thanks for your response. This is what I'm doing, going to settings gear > extension settings > By the file type, then I copy simpest of the code and paste it to settings.json. The problem is that this code works when I specify default colors but it doesn't work with the custom colors I defined earlier. So I thought that it would be easier to change the default colors definition. Is that possible somehow?

**Comment by mondersky** [comment]
you're welcome. Can you send me a copy of your colortabs settings code

**Comment by Zwornik** [comment]
this is the whole code when I open By File Type link
```
{
	"editor.fontFamily": "JetBrains Mono",
	"terminal.integrated.fontFamily": "monospace",
	"editor.accessibilitySupport": "off",
	"files.autoSave": "afterDelay",
	"editor.formatOnSave": true,
	"workbench.iconTheme": "material-icon-theme",
	"prettier.jsxSingleQuote": true,
	"prettier.singleQuote": true,
	"prettier.useTabs": true,
	"editor.wordWrap": "on",
	"breadcrumbs.enabled": false,
	"editor.linkedEditing": true,
	"editor.defaultFormatter": "esbenp.prettier-vscode",
	"[html]": {
		"editor.defaultFormatter": "vscode.html-language-features"
	},
	"emmet.syntaxProfiles": {
		"html": {
			"inline_break": 2
		}
	},
	"prettier.bracketSameLine": true,
	"explorer.confirmDelete": false,
	"explorer.confirmDragAndDrop": false,
	"liveServer.settings.donotShowInfoMsg": true,
	"window.zoomLevel": -1,
	"liveServer.settings.AdvanceCustomBrowserCmdLine": "C:\\Program Files\\Google\\Chrome Dev\\Application\\chrome.exe",
	"[python]": {
		"editor.formatOnType": true
	},
	"workbench.colorTheme": "Monokai",
	"tabsColor.byFileType": {
	
		"ts": {
		  "backgroundColor": "yellow2",
		  "fontColor": "white"
		},	  
		"html": {
		  "backgroundColor": "blue2",
		  "fontColor": "white"
		},
		"css": {
		  "backgroundColor": "blue2",
		  "fontColor": "ffffff"
		},
		"spec.ts": {
		  "backgroundColor": "Bronz",
		  "fontColor": "black"
		}
	  }
}
```

**Comment by mondersky** [comment]
in order to use a custom color in settings, use values like you would do on CSS
example:
"ts": {
		  "backgroundColor": "#FFFF00",
		  "fontColor":" rgb(255,0,0)"
		},

**Comment by Zwornik** [comment]
That works perfectly. Thanks a lot! :) 
This extension is great!
Best of luck!

**Comment by mondersky** [comment]
you're welcome, if you like the extension please leave a review on the vs code extension page, that will help a lot. Thanks

**Comment by mondersky** [comment]
can you send me a whole copy of the settings containing that line

**Comment by Zwornik** [comment]
"workbench.colorTheme": "Monokai",
    "tabsColor.byFileType": {

        "ts": {
          "backgroundColor": "#b7a115",
          "fontColor": "#ffffff"
        },
        "html": {
          "backgroundColor": "#2f56b1",
          "fontColor": "#000000"
        },
        "css": {
          "backgroundColor": "#4fb125",
          "fontColor": "rgb(255,0,0)"
        },
        "spec.ts": {
          "backgroundColor": "#b06d21",
          "fontColor": "#000000"
        }
      }

czw., 9 mar 2023 o 09:01 Brahim Rezzag ***@***.***>
napisał(a):

**Comment by mondersky** [comment]
try right click on one of the tabs in which the font color is not correct, and chose color>none then tell me what happens

**Comment by Zwornik** [comment]
It works correctly today, maybe it needed a restart of the VSC. Thanks for this extension and your help. I have just left a comment.

**Comment by mondersky** [comment]
thanks
