### ISSUE TITLE
macOS macOS!!

### ISSUE THREAD

**Issue by seabye** [mondersky/tabscolor-vscode#27]
Hey, can you look into Mac OS compatibility. I've been watching for a year, and still no support. ╮(╯_╰)╭

**Comment by mondersky** [comment]
Unfortunately, I haven't been able to find a viable solution yet. 
You can try implementing the suggested solution by @kobilee to make the extension compatible with your Mac  [#issuecomment-1528018985](https://github.com/mondersky/tabscolor-vscode/issues/6#issuecomment-1528018985)

**Comment by seabye** [comment]
@mondersky ٩( ᐛ )و Thank you, this method can be used. After pulling the code, enter the directory and execute ‘npm install; npx vsce package;’ to build and get ‘.vsix’, and then select local installation in VSCode. I think if it cannot be solved in the short term, and the local installation is always effective, this can be written in Readme, or even provide .vsix download. I really like the creative idea of this extension plugin! Thank you for your work.

**Comment by hchauvat-owkin** [comment]
FYI, It seems to be working just fine on my mac! I do need to reload the app after changing any setting though:
<img width="575" alt="Capture d’écran 2024-08-05 à 11 08 22" src="https://github.com/user-attachments/assets/150c1296-8bae-4804-9400-b7ffe5e851b4">

**Comment by mondersky** [comment]
@hchauvat-owkin thanks for reporting this, did you apply any specific method to make it work ?

**Comment by mondersky** [comment]
follow the MacOs incompatibility thread here #6
