### ISSUE TITLE
Publish to OpenVSX?

### ISSUE THREAD

**Issue by janpio** [mondersky/tabscolor-vscode#28]
I would love to use your extension with Gitpod, but they have to use [OpenVSX](https://open-vsx.org/) instead of the official marketplace: https://www.gitpod.io/blog/open-vsx-in-gitpod

Are you maybe open to publishing to [OpenVSX](https://open-vsx.org/)?

**Comment by mondersky** [comment]
published https://open-vsx.org/extension/mondersky/tabscolor

**Comment by janpio** [comment]
Unfortunately:
<img width="397" alt="image" src="https://github.com/mondersky/tabscolor-vscode/assets/183673/f95a8f17-9b5b-4b4f-ac3d-0abeb50603cb">
https://code.visualstudio.com/docs/editor/vscode-web#_extensions

**Comment by mondersky** [comment]
too bad. In fact the extension operates by patching vs code installation files, it's unlikely that it will function on web

**Comment by janpio** [comment]
Makes sense then.

Publishing to OpenVSX is of course still useful for all the other people not wanting (or being able) to use the official marketplace 👍
