### ISSUE TITLE
Color not changing

### ISSUE THREAD

**Issue by pep248** [mondersky/tabscolor-vscode#30]
When I apply a color using right click and selecting a color, it displays a message:
---tab updated---
but no color is actually applied.

**Comment by OzakIOne** [comment]
Same here

Windows 11, WSL

Tabs color:
Version: 0.1.34

VSCode:
Version: 1.85.1 (user setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by mondersky** [comment]
@pep248 please share you vs code version and os

**Comment by mondersky** [comment]
@OzakIOne the extension fails to activate on WSL follow this issue here #3

**Comment by OzakIOne** [comment]
> @OzakIOne the extension fails to activate on WSL follow this issue here #3

I tried this setting and it didn't change anything, still behaves the same as before

**Comment by pep248** [comment]
> @pep248 please share you vs code version and os

Version: 1.85.1 (user setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621



> > @OzakIOne the extension fails to activate on WSL follow this issue here #3
> 
> I tried this setting and it didn't change anything, still behaves the same as before

Same here

**Comment by mondersky** [comment]
the WSL issue remains unresolved. Please stay updated on its status by monitoring it here #3
