### ISSUE TITLE
Tab-Color doesn't move on drag and drop of a tab in splitview

### ISSUE THREAD

**Issue by b3nks** [mondersky/tabscolor-vscode#33]
When the third tab is colored in a split view in red and i move it to the first place, the new first tab is without color, the new third is red.

I would expect the tab to keep the color when moved.

**Comment by mondersky** [comment]
thanks for reporting this, it seems that this issue occurs whether in split view or not, I'll look to it soon

**Comment by b3nks** [comment]
A workaround seems to be to drag a color tab to another split view tile and then drag it back to the final destination tab menü. Then the color is correct in the end.

**Comment by mondersky** [comment]
I have updated the extension with a fix to the issue, can you please confirm if it works on your end.
The adjustments should be applied once you close and reopen VS Code

**Comment by b3nks** [comment]
Nice - I can confirm.
