### ISSUE TITLE
Tabs change colors only after VS Code restart

### ISSUE THREAD

**Issue by xxxxxxbox** [mondersky/tabscolor-vscode#34]
I like the idea of your plugin. This is one of the plugins I need most, but unfortunately I haven't been able to make it work for several months now. I've tried to do so on three different computers. The number of bugs in the plugin is huge and with each new update, I hope that they have been fixed and I will be able to use it.  But so far, no luck.

I will describe my experience with the latest version 0.2.2 from 12/04.

I deleted the old version of Tabs Color. After that, I restarted Vs Code and installed the latest version of Tabs Color. After that, I restarted Vs Code again. 
**Next, I choose a color for several tabs (green, red, blue). At the same time, the tabs do not change their colors. If I restart VS Code, only then  I see all my set tab colors. But at the same time, if I set new tab colors using menu, they do not change color. I see the new tab colors only after the next VS Code restart. And so on endlessly.**
I've tried disabling all my plugins to make sure they don't interfere. I even tried reinstalling Vs Code. Disabling plugins and reinstalling did not help.

One more observation. I deleted the plugin and restarted VS Code. But the tabs remained colored. I restarted Vs Code again and the tabs reset the color. After that, I reinstalled the plugin and restarted Vs Code once again. All tabs were unpainted. I tried changing the color of one tab. The tab, as I wrote above, did not change the color. I restarted VS Code and found that not one, but many tabs became colored. The color has changed not only the tab that I changed last, but also those tabs that I experimented with before uninstalling the plugin.

Another bug. If you drag a colored tab into a separate window, its color is reseted. Today you wrote that you solved a similar problem, but I can't confirm it.

All I wrote above I  testing working locally. Even locally, I can't get Tabs Color to work. But most of the time I work using SSH Remote. It's even worse there. I read that there are problems with remote work and I don't even hope that I can use Tabs Color with SSH remote.  While working in SSH remote mode  colors of the tabs cannot be set manually. Bugs of Tabs Color while remote work are even more mysterious and difficult to diagnose. For example, I set the color for the active tab in the settings file. The color of the active tab does not change when working remotely. Rebooting Vs Code does not help. I can work for several hours with unpainted tabs, and then at some point the active tab in the first position in a separate window becomes colored.   If you make another tab active, the colored backlight will still remain on the first tab. (Note. As for remote work, I tested it on the previous version of the plugin).

I am grateful to you for the idea of the plugin and for your work. O'm looking forward gettting Color Tabs someday, which I can make work.

Version: 1.88.1 (user setup)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:41:02.734Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.19045

Tabs Color 0.2.2. / 2024-04-12

**Comment by xxxxxxbox** [comment]
Hi there.
Please find to demos of bugs desribed above.

![tc-demo2](https://github.com/mondersky/tabscolor-vscode/assets/56993366/1b34fda8-a10f-4fbb-8ee2-d022bc255e75)

![tc-demo1](https://github.com/mondersky/tabscolor-vscode/assets/56993366/97914937-17d9-48f1-83e9-05d278360ddf)

**Comment by xxxxxxbox** [comment]
Demo2:
![tc-demo2](https://github.com/mondersky/tabscolor-vscode/assets/56993366/1b34fda8-a10f-4fbb-8ee2-d022bc255e75)

**Comment by mondersky** [comment]
I appreciate the effort you're investing in enhancing this extension. It appears that the issues you're encountering are specific to your environments. If you're willing, I'd be happy to arrange a screen sharing session to observe the extension's behavior on one of your PCs and troubleshoot these problems. Please let me know if you're open to this idea

**Comment by xxxxxxbox** [comment]
Thanx for reply.
I'm ready to share my screen to show the extension's behavior.

v. 0.2.4 still has the Issue.
I've sent you email with my contact information,

**Comment by Turgon-Aran-Gondolin** [comment]
I got similar behavior, but after installing the extension and applying the color, I also got an error saying my vscode installation was corrupted. I have to reinstall it.
