### ISSUE TITLE
What strange window do I see after installing the plugin?

### ISSUE THREAD

**Issue by Cleverscript** [mondersky/tabscolor-vscode#36]
![Screenshot_20240517_112159](https://github.com/mondersky/tabscolor-vscode/assets/204266/29b080a9-4c9b-4e2d-8745-8b62ffc6695b)
The plugin doesn't work, apparently because I didn't enter my password in this window? Why should I enter it?

The Policy KitProject  https://hal.freedesktop.org/docs/PolicyKit/ points to 404

what the hell?

---
Ubuntu 22.04, KDE

**Comment by mondersky** [comment]
The extension operates by modifying your VS Code files; if they're read-only, you might receive a prompt asking for permission.
