### ISSUE TITLE
Not working anymore after VSCode update v1.94.0

### ISSUE THREAD

**Issue by Vince1024** [mondersky/tabscolor-vscode#38]
Hi,

Thanks for your gerat job with this extention.

After my VsCode update to 1.94.0 the Tabs Color is not working anymore.

I don't see any problems in the log !

Do other users report this or did I do something wrong ?

Thanks
Vincent.

**Comment by bitsundbaeume** [comment]
After an update I am prompted for my admin password. If i refuse to type it in, a file cannot be written and the colors are gone. If I give root access, after a restart of code the colors are back there.

**Comment by b3nks** [comment]
I user Debian 12.5 bookworm and am prompted each time i start code. IF you use windows you may want to start code as an admin, if you trust your code setup once to get back the colors.

**Comment by b3nks** [comment]
@mondersky would be great if the config wrote to the file without root access.

**Comment by mondersky** [comment]
Thanks for reporting this issue. Could you please confirm if the most recent update of the extension is working for you? Your feedback would be appreciated!

**Comment by b3nks** [comment]
@mondersky v0.2.5 works on a test debian, but only after authorization.

**Comment by mondersky** [comment]
@b3nks The extension requires patching one of VSCode's installation files. On systems where the directory is protected, you may be prompted to authorize the change. This is expected behavior, as it's the only way to apply the patch. Are you saying this issue didn't occur before version 1.94.0?

**Comment by b3nks** [comment]
No - I had the root authorisation prompt from the first update on.
