### ISSUE TITLE
Add the ability to put color on the files in the Explorer

### ISSUE THREAD

**Issue by morceaudebois** [mondersky/tabscolor-vscode#4]
That’d be great if we could add color to the files in the files explorer as well (akin to what macOS does in the Finder with color tags).

I love this kind of thing and I’m definitely gonna use it, thank you for your work!

**Comment by mondersky** [comment]
Thanks for the suggestion, I like the idea, it would definitely fit in a new extension. 
I am happy that you like the extension :)
