### ISSUE TITLE
Extension stopped working after last update

### ISSUE THREAD

**Issue by IcyFoxe** [mondersky/tabscolor-vscode#44]
Hello, this extension seems to have stopped working (both Win & Mac) after the last (0.2.6) update.
I mentioned this in a commit comment, but just in case you might have not seen it, I'm posting it here.

**Comment by mondersky** [comment]
thanks for your quick intervention. I've fixed the issue. Check version 0.2.7

**Comment by IcyFoxe** [comment]
Perfect, works again!

**Comment by IcyFoxe** [comment]
@mondersky Aaah I'm sorry, I was too quick to report :D
It is KINDA working currently - after restarting, I see the colors again, but there's no reactivity. If I set a color it doesn't change until I restart VSCode..

**Comment by mondersky** [comment]
after restarting, does it become reactive ?

**Comment by IcyFoxe** [comment]
No, after restarting previous changes are visible. Any new changes require another restart currently.

**Comment by mondersky** [comment]
Strangely I am unable to reproduce the issue on my vscode. Is the issue occurring on both mac & windows ?

**Comment by IcyFoxe** [comment]
Checked on Windows and there it's working fine. So yeah, it seems to be only a Mac issue. However v0.2.5 worked on Mac just fine.

**Comment by mondersky** [comment]
I just uploaded v0.2.8 it contains the same code as v0.2.5 can you check now ?

**Comment by IcyFoxe** [comment]
Alright, I tried and it still keeps happening. I downgraded to version 0.2.5 and it also keeps happening. So the issue must be something else at this point, but the strange thing is that today when I installed the extension for the first time (when it was at version 0.2.5), everything was working fine on Mac.

So 2 options come to mind for me:
- since I wasn't using the extension for too long, it might've broken on v0.2.5 eventually, if I kept using it for few days, maybe after relaunch or after "restart extension host" command, etc.. Not sure, can't confirm that
- other option might be that v0.2.6 migh have left some "permanent damage" after update? That's just speculation, since I don't know how this extension works, but the "Your Code installation is corrupt" message tells me it's not the usual approach

That's all I can report you, since I wasn't using the extension for very long. Hope it helps in some way.

**Comment by mondersky** [comment]
Thank you for the detailed report! I'll try to find a Mac where the issue occurs and debug it there. In the meantime, you can run the command **remove patch** to clear your current patch, which will reset things and might provide us with some clues

**Comment by xxxxxxbox** [comment]
> Thank you for the detailed report! I'll try to find a Mac where the issue occurs and debug it there. In the meantime, you can run the command **remove patch** to clear your current patch, which will reset things and might provide us with some clues

It's not a Mac Issue. Tabs are not reactive - I have had this problem on Windows for a long time. I noticed it 6-12 months ago and it is present in version 0.2.8 as well. This is one of those problems that has prevented me from using Tabs Color since day one I discovered this plugin. I've been waiting for months for a working version to finally be available. I wondered why no one else was complaining, but finally I came across a message that I wasn't the only one with this problem.
![tabs_color_screen1](https://github.com/user-attachments/assets/0f841ae6-816f-45c2-a9c8-f566e2fcc08a)

I recorded a detailed video of this problem in VSCode on Windows.
Thanks for support. Hope this helps.

**Comment by IcyFoxe** [comment]
> Thank you for the detailed report! I'll try to find a Mac where the issue occurs and debug it there. In the meantime, you can run the command **remove patch** to clear your current patch, which will reset things and might provide us with some clues

"remove patch" did not help. Still behaves the same, even after multiple program restarts.

**Comment by GiurlaniDev** [comment]
I'm also having this issue after updating my vsc to the latest version (1.95.0) and also I have TabsColor (v0.2.8).

Same problem as the .gif IcyFoxe posted. I'm on Windows 10 64bit.

**Comment by mondersky** [comment]
@IcyFoxe @GiurlaniDev I have updated a potential fix to the issue, can you update to 0.2.9 and tell me it it's still happening ?

**Comment by GiurlaniDev** [comment]
> @IcyFoxe @GiurlaniDev I have uploaded a potential fix to the issue, can you update to 0.2.9 and tell me it it's still happening ?

It works fine now! Thank you @mondersky 🥇

**Comment by GiurlaniDev** [comment]
@mondersky 
Currently on TabsColor v0.2.11, problem reocurring. Sorry to be a bother, I'm not sure what's wrong with it now, it was previously working when I commented last week, but seemingly broke yet again.

Appreciate all the effort, the extension really is utile and a lifesaver (when it does function hehe)

Refer to the video attached for details.

https://github.com/user-attachments/assets/daac9e70-3d15-4ca5-a2c5-e0facad68e1f

**Comment by GiurlaniDev** [comment]
@mondersky
Currently on TabsColor v0.2.11, problem reocurring. Sorry to be a bother, I'm not sure what's wrong with it now, it was previously working when I commented last week, but seemingly broke yet again.

Appreciate all the effort, the extension really is utile and a lifesaver (when it does function hehe)

Refer to the video attached for details.

https://github.com/user-attachments/assets/4000f661-76a7-4515-91fa-b6d3afa80f3a

**Comment by mondersky** [comment]
@GiurlaniDev thanks for reporting this and no problem, quite the opposite you are helping me make this extension more stable. Based on what I saw from the video, the problem seems to be related to unsaved files tabs, do you confirm this ?

**Comment by GiurlaniDev** [comment]
> @GiurlaniDev thanks for reporting this and no problem, quite the opposite you are helping me make this extension more stable. Based on what I saw from the video, the problem seems to be related to unsaved files tabs, do you confirm this ?

Yes! It doesn't work on unsaved file tabs

**Comment by mondersky** [comment]
@GiurlaniDev This issue doesn't seem to be related to the last updates, it looks like it has always been there. Follow this thread here #48
