### ISSUE TITLE
TabsColor does not change colors for "quickly opened tabs".

### ISSUE THREAD

**Issue by xxxxxxbox** [mondersky/tabscolor-vscode#46]
If you quickly open files in Vs Code from the list in the panel on the left, they all open in the same single tab. This is done specially so that only useful tabs stay opened in the program. New tabs for files are opened only if the file is dragged with the mouse or if a lot of time has passed since the previous tab was opened.

Tabs Color  does not know how to handle tabs that are openinig quickly. Every time I set the color for a quick-open tab, the color doesn't change.  But if I drag the same tab into the right panel with my mouse, the tab's color will immediately change. The same thing happens if I type anything on a quick opened tab. Please find enclosed gif screen recordings.

Tabs Color v0.2.11, Windows.
The same behavior for local folder and when working with SSH Remote.

![Code_t6lp6Xmkua](https://github.com/user-attachments/assets/038a9618-bd2e-4d2a-a126-6ac1c1261373)

**Comment by xxxxxxbox** [comment]
v.0.2.12 added "Support tabs in preview mode".

It's seems to fix issue but not for tabs colored by directory.
Files listed in settings with tabsColor.byDirectory{} has no color in preview mode.

**Comment by mondersky** [comment]
the preview mode coloring is now possible but with limitations, follow the thread here #48
