### ISSUE TITLE
Extension tries to execute something as superuser?

### ISSUE THREAD

**Issue by alexanderadam** [mondersky/tabscolor-vscode#8]
I'm a bit surprised. Is this documented somewhere?

Is this what you meant by

> this extension uses patching in order to allow tabs style editing

**Comment by mondersky** [comment]
Yes, the extension applies a patch to a vs code file, if the file is read only it should ask for permission. Patching is the only way to get access to tabs style on vs code as the API doesn't offer any solution for this

**Comment by alexanderadam** [comment]
Thank you for your response.
Is there an upstream ticket for VSCode to allow changing tab colours via API?

**Comment by mondersky** [comment]
You're welcome.
The last time I searched there was no ticket about that. This extension is an alternative until such an option becomes available
